os: osx
language: generic
osx_image: xcode10.1
before_script:
- git clone https://github.com/flutter/flutter.git -b beta
- export PATH=$PATH:`pwd`/flutter/bin
script:
- flutter doctor
- flutter packages get
- flutter test
deploy:
  provider: script
  script:
    - flutter test
  on:
    tags: true
cache:
  directories:
  - "$HOME/.pub-cache"
notifications:
  slack:
    secure: B54QsEmhAFMO+4nTl3jkuL63beE7SAdXusKbSJiKGTqzuGxrQz2cvlU8EU5pNtELhaXCPuEOPN2qs0YIeF+61WlWPSyiJEyv16YGchyvNS05pWsFUyk8FVUldqxpq0O9WUK7L/eUMEYrJQZWSFeXy50HMipdEMSC2+XU5uMvcW4J/c6OOt3V+f2DxZnx9vbJl+m5bQLq2b9zrDZ8MMKqWfA57TXzLNXpidcM1xwmbMYnnS9unA/d471bgeBv4DuPaJOl51l+H84umPzEWGRf/0Izp9QONyTVg5GVhlwRL787Gh2Cj2rHI6yJQXjDwLDCES6+CRBg2UF0yIKSzic1Q8UsbSji0CCjyaHLq7vb7vUx0JPzRUGODDrqoFO+de/wMvh4jO+SEYEA2cedeuK9e8Z0qs/4phEL1L6KnNO9E8CdXE9MFCSw/SAeyulU3B+c2ov99Yl/izsqmfI8JpS3eGfK4u3+8DHxiYdOXe3FtzrvdL+4L4DppFyulvJ/NPCu9nKNw+Q/FOxdZgLXHczzZ0IQtWf7elvJ8uAuK1JAEhdF7qcHbXf7m2SNCiPa+wlT8EWGJ5SKkx6qyaau3p43EpGDWRMnLyNFmspYKxjp7ydNlHAZOVNy4oT31e0sdNGxlFK4p0kZ8ovr1NlTe3Q0fJM1essXEiJY3zhr/T8wnm8=